name: Test docker image CI speed

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'server/Dockerfile'
      - '.github/.workflows/test-docker-cache.yml'
  pull_request:
    paths:
      - 'server/Dockerfile'
      - '.github/.workflows/test-docker-cache.yml'

jobs:
  test-image:
    name: Server docker image CI
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
    - uses: actions/checkout@v4

    - name: Build server image
      run: docker compose build
      working-directory: ./server

    - name: Run server with docker-compose
      run: docker compose up -d
      working-directory: ./server

    - name: Check server container is up and running
      run: curl --retry 5 --retry-all-errors http://localhost:8071/api/v1/health/

    - name: Display server container logs
      if: failure()
      run: docker compose logs backend
      working-directory: ./server

    - name: Terminate docker compose created containers
      if: always()
      run: docker compose down -v
      working-directory: ./server
