name: Java Lint
on:
  pull_request:
    paths:
      - "java/**"
      - "lib-openapi.json"
  push:
    branches:
      - main
    paths:
      - "java/**"
      - "lib-openapi.json"

jobs:
  dotnet:
    name: Java Lint
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: useblacksmith/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build
        run: |
          cd java
          ./gradlew build
