name: Python Release

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Mega Releaser
    types:
      - completed

jobs:
  build:
    name: Build distributions
    runs-on: blacksmith-4vcpu-ubuntu-2404
    environment: release

    steps:
      - uses: actions/checkout@v4

      - uses: useblacksmith/setup-python@v6
        name: Install Python
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          cd python
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt

      - name: Install build
        run: |
          cd python
          python -m pip install build

      - name: Build distributions
        run: |
          cd python
          python -m build

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TWINE_PASSWORD }}
          packages_dir: python/dist
