name: Typos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  typos:
    name: Check for typos
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.33.1
