name: Go Lint
on:
  pull_request:
    paths:
      - "go/**"
      - "go.sum"
      - "go.mod"
      - "lib-openapi.json"
  push:
    branches:
      - main
    paths:
      - "go/**"
      - "go.sum"
      - "go.mod"
      - "lib-openapi.json"

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: useblacksmith/golangci-lint-action@v6
        with:
          version: latest
          working-directory: go
          args: --verbose
