name: JavaScript Lint

on:
  pull_request:
    paths:
      - "javascript/**"
      - "lib-openapi.json"
      - '.github/workflows/javascript-lint.yml'
  push:
    branches:
      - main
    paths:
      - "javascript/**"
      - "lib-openapi.json"
      - '.github/workflows/javascript-lint.yml'

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4

      - uses: useblacksmith/setup-node@v5
        with:
          node-version: 'latest'
          registry-url: 'https://registry.npmjs.org'

      - name: Install modules
        run: |
          cd javascript
          yarn

      - name: Lint
        run: |
          cd javascript
          yarn run lint

      - name: Test
        run: |
          cd javascript
          yarn run test
