name: Ruby Lint

on:
  pull_request:
    paths:
      - "ruby/**"
      - "lib-openapi.json"
      - '.github/workflows/ruby-lint.yml'
  push:
    branches:
      - main
    paths:
      - "ruby/**"
      - "lib-openapi.json"
      - '.github/workflows/ruby-lint.yml'

jobs:
  dotnet:
    name: Ruby Lint
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: useblacksmith/setup-ruby@v2
        with:
          ruby-version: 3.4.2

      - name: Install dependencies
        run: |
          cd ruby
          bundler install

      - name: Build
        run: |
          cd ruby
          bundler exec rake build

      - name: Test
        run: |
          cd ruby
          bundler exec rspec spec
