name: Rust Lib Security

on:
  push:
    branches:
    - main
    paths:
      - 'rust/**/Cargo.toml'
      - 'rust/**/Cargo.lock'
      - '.github/workflows/rust-security.yml'
  pull_request:
    paths:
      - 'rust/**/Cargo.toml'
      - 'rust/**/Cargo.lock'
      - '.github/workflows/rust-security.yml'

jobs:
  security_audit:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          manifest-path: rust/Cargo.toml
