name: Test docker image CI speed

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - '.github/workflows/test-docker-cache.yml'
  pull_request:
    paths:
      - 'server/**'
      - '.github/workflows/test-docker-cache.yml'
      

jobs:
  test-image:
    name: Server docker image CI
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
    - uses: actions/checkout@v4

    - name: dbg image (before build)
      run: docker image ls local-svix-server
    
    - name: Build docker image
      uses: useblacksmith/build-push-action@v1
      with:
        push: false
        tags: local-svix-server
        context: server

    - name: dbg image (after build)
      run: docker image ls local-svix-server

    - name: Pull docker image
      run: docker compose pull
      working-directory: ./server

    - name: Run server with docker-compose
      run: docker compose up -d
      working-directory: ./server

    - name: Check server container is up and running
      run: curl --retry 5 --retry-all-errors http://localhost:8071/api/v1/health/

    - name: Display server container logs
      if: failure()
      run: docker compose logs backend
      working-directory: ./server

    - name: Terminate docker compose created containers
      if: always()
      run: docker compose down -v
      working-directory: ./server
